### ISSUE TITLE
next(chunks)

### ISSUE THREAD

**Issue by mohana-martin** [EnergieID/KNMI-py#12]
I get the following error:

Traceback (most recent call last):

  File "<ipython-input-100-c31de365c742>", line 1, in <module>
    knmi.get_day_data_raw(stations=[240],start="20120101",end="20130101")

  File "c:\python\python37\lib\site-packages\knmi\knmi.py", line 62, in get_day_data_raw
    disclaimer, stations, legend, data = parse_day_data(raw=r.text)

  File "c:\python\python37\lib\site-packages\knmi\parsers.py", line 30, in parse_day_data
    stations_raw = next(chunks)

StopIteration

no matter what settings or function I use.. In this example I tried the following:
```
import knmi
knmi.get_day_data_raw(stations=[240],start="20120101",end="20130101")
```

**Comment by justinzw2xep** [comment]
I experienced the same error.

**Comment by justinzw2xep** [comment]
Same problem, is this because of the API issues at KNMI maybe?

**Comment by OLM144** [comment]
Same problem here, it was working few months ago without any problem. Any ideas how to fix this ?

**Comment by MickMack82** [comment]
According to KNMI the new solution should be in place now. I also noticed that they removed the remark on their site regarding the fact the service isn't working. It seems the link to the data is changed. If that is the only thing it should be a straightforward fix 8n the script.

**Comment by wesleyverbruggen** [comment]
Has anyone been able to get it to work yet? I can't seem to work out a solution.

**Comment by jschuitemaker** [comment]
# JSON output to the rescue
I'm not sure if this is a new feature, but you can ask the API for a JSON result instead of this table like response. That would make it much easier & safer to process.

So my advice would be to abondon this lib and go for a simple request like the one below, with the fmt parameter.

`wget -O - --no-check-certificate --post-data="fmt=json&start=20210101&end=20210101&stns=260" https://www.daggegevens.knmi.nl/klimatologie/daggegevens`

This will give you: 
```
[{"station_code":260,"date":"2021-01-01T00:00:00.000Z","DDVEC":225,"FHVEC":21,"FG":21,"FHX":30,"FHXH":6,"FHN":10,"FHNH":1,"FXX":60,"FXXH":15,"TG":30,"TN":-35,"TNH":3,"TX":57,"TXH":14,"T10N":-30,"T10NH":6,"SQ":9,"SP":12,"Q":194,"DR":0,"RH":0,"RHX":0,"RHXH":1,"PG":10084,"PX":10113,"PXH":24,"PN":10059,"PNH":1,"VVN":0,"VVNH":2,"VVX":70,"VVXH":11,"NG":7,"UG":92,"UX":98,"UXH":1,"UN":85,"UNH":15,"EV24":2}] 
```

# Parser
If you want to keep using this library, below are some of my findings and possible changes to fix things. 

* One of the issues is the changed URL. I could not get the old one working, but I did with the new one (https://www.daggegevens.knmi.nl/klimatologie/daggegevens), however you need some tweaks, see below. 

* One issue is with dates (start/end). According to the KNMI website https://www.knmi.nl/kennis-en-datacentrum/achtergrond/data-ophalen-vanuit-een-script these are both REQUIRED (verplicht) and no longer optional as this library is expecting. If you omit either start or end, you will simply get the website page as response, not the formatted tables this library wants to parse. You can try that out with the command below (run from bash). Omit the end parameter and you will get HTML as a response. If you run this with start & end, you will get a table like reponse (see example at bottom)

`wget -O - --no-check-certificate --post-data="start=20210101&end=20210101&stns=260" https://www.daggegevens.knmi.nl/klimatologie/daggegevens`

Fixes needed, as far as I could figure out:

* Correct the URLs (and if possible make them configurable)
* Throw exception when required parameters are missing
* Improve parsers.py:
** There are now two disclaimers (one in dutch, one in english). 
** The chunk_splitter expects empty # lines as seperator between parts, but they are sometimes missing. 


Example where in between the station line (391) and the first line of the legend, there is no empty line. As a result, legend lines will be added to the stations chunk with exceptions as a result.


```
# 391         6.197       51.498      19.50       Arcen       
# DDVEC     : Vectorgemiddelde windrichting in graden (360=noord; 90=oost; 180=zuid; 270=west; 0=windstil/variabel). Zie http://www.knmi.nl/kennis-en-datacentrum/achtergrond/klimatologische-brochures-en-boeken / Vector mean wind direction in degrees (360=north; 90=east; 180=south; 270=west; 0=calm/variable)

```

# ALL data from wget 

```
# Opmerking: door stationsverplaatsingen en veranderingen in waarneemmethodieken zijn deze tijdreeksen van uurwaarden mogelijk inhomogeen! Dat betekent dat deze reeks van gemeten waarden niet geschikt is voor trendanalyse. Voor studies naar klimaatverandering verwijzen we naar de gehomogeniseerde dagreeksen <http://www.knmi.nl/nederland-nu/klimatologie/daggegevens> of de Centraal Nederland Temperatuur <http://www.knmi.nl/kennis-en-datacentrum/achtergrond/centraal-nederland-temperatuur-cnt>.
# 
# SOURCE: ROYAL NETHERLANDS METEOROLOGICAL INSTITUTE (KNMI)
# Comment: These time series are inhomogeneous because of station relocations and changes in observation techniques. As a result these series are not suitable for trend analysis. For climate change studies we refer to the homogenized series of daily data <http://www.knmi.nl/nederland-nu/klimatologie/daggegevens> or the Central Netherlands Temperature <http://www.knmi.nl/kennis-en-datacentrum/achtergrond/centraal-nederland-temperatuur-cnt>.
# 
# STN         LON(east)   LAT(north)  ALT(m)      NAME
# 209         4.518       52.465      0.00        IJmond      
# 210         4.430       52.171      -0.20       Valkenburg Zh
# 215         4.437       52.141      -1.10       Voorschoten 
# 225         4.555       52.463      4.40        IJmuiden    
# 235         4.781       52.928      1.20        De Kooy     
# 240         4.790       52.318      -3.30       Schiphol    
# 242         4.921       53.241      10.80       Vlieland    
# 248         5.174       52.634      0.80        Wijdenes    
# 249         4.979       52.644      -2.40       Berkhout    
# 251         5.346       53.392      0.70        Hoorn Terschelling
# 257         4.603       52.506      8.50        Wijk aan Zee
# 258         5.401       52.649      7.30        Houtribdijk 
# 260         5.180       52.100      1.90        De Bilt     
# 265         5.274       52.130      13.90       Soesterberg 
# 267         5.384       52.898      -1.30       Stavoren    
# 269         5.520       52.458      -3.70       Lelystad    
# 270         5.752       53.224      1.20        Leeuwarden  
# 273         5.888       52.703      -3.30       Marknesse   
# 275         5.873       52.056      48.20       Deelen      
# 277         6.200       53.413      2.90        Lauwersoog  
# 278         6.259       52.435      3.60        Heino       
# 279         6.574       52.750      15.80       Hoogeveen   
# 280         6.585       53.125      5.20        Eelde       
# 283         6.657       52.069      29.10       Hupsel      
# 285         6.399       53.575      0.00        Huibertgat  
# 286         7.150       53.196      -0.20       Nieuw Beerta
# 290         6.891       52.274      34.80       Twenthe     
# 308         3.379       51.381      0.00        Cadzand     
# 310         3.596       51.442      8.00        Vlissingen  
# 311         3.672       51.379      0.00        Hoofdplaat  
# 312         3.622       51.768      0.00        Oosterschelde
# 313         3.242       51.505      0.00        Vlakte van De Raan
# 315         3.998       51.447      0.00        Hansweert   
# 316         3.694       51.657      0.00        Schaar      
# 319         3.861       51.226      1.70        Westdorpe   
# 323         3.884       51.527      1.40        Wilhelminadorp
# 324         4.006       51.596      0.00        Stavenisse  
# 330         4.122       51.992      11.90       Hoek van Holland
# 331         4.193       51.480      0.00        Tholen      
# 340         4.342       51.449      19.20       Woensdrecht 
# 343         4.313       51.893      3.50        Rotterdam Geulhaven
# 344         4.447       51.962      -4.30       Rotterdam   
# 348         4.926       51.970      -0.70       Cabauw Mast 
# 350         4.936       51.566      14.90       Gilze-Rijen 
# 356         5.146       51.859      0.70        Herwijnen   
# 370         5.377       51.451      22.60       Eindhoven   
# 375         5.707       51.659      22.00       Volkel      
# 377         5.763       51.198      30.00       Ell         
# 380         5.762       50.906      114.30      Maastricht  
# 391         6.197       51.498      19.50       Arcen       
# DDVEC     : Vectorgemiddelde windrichting in graden (360=noord; 90=oost; 180=zuid; 270=west; 0=windstil/variabel). Zie http://www.knmi.nl/kennis-en-datacentrum/achtergrond/klimatologische-brochures-en-boeken / Vector mean wind direction in degrees (360=north; 90=east; 180=south; 270=west; 0=calm/variable)
# FHVEC     : Vectorgemiddelde windsnelheid (in 0.1 m/s). Zie http://www.knmi.nl/kennis-en-datacentrum/achtergrond/klimatologische-brochures-en-boeken / Vector mean windspeed (in 0.1 m/s)
# FG        : Etmaalgemiddelde windsnelheid (in 0.1 m/s) / Daily mean windspeed (in 0.1 m/s)
# FHX       : Hoogste uurgemiddelde windsnelheid (in 0.1 m/s) / Maximum hourly mean windspeed (in 0.1 m/s)
# FHXH      : Uurvak waarin FHX is gemeten / Hourly division in which FHX was measured
# FHN       : Laagste uurgemiddelde windsnelheid (in 0.1 m/s) / Minimum hourly mean windspeed (in 0.1 m/s)
# FHNH      : Uurvak waarin FHN is gemeten / Hourly division in which FHN was measured
# FXX       : Hoogste windstoot (in 0.1 m/s) / Maximum wind gust (in 0.1 m/s)
# FXXH      : Uurvak waarin FXX is gemeten / Hourly division in which FXX was measured
# TG        : Etmaalgemiddelde temperatuur (in 0.1 graden Celsius) / Daily mean temperature in (0.1 degrees Celsius)
# TN        : Minimum temperatuur (in 0.1 graden Celsius) / Minimum temperature (in 0.1 degrees Celsius)
# TNH       : Uurvak waarin TN is gemeten / Hourly division in which TN was measured
# TX        : Maximum temperatuur (in 0.1 graden Celsius) / Maximum temperature (in 0.1 degrees Celsius)
# TXH       : Uurvak waarin TX is gemeten / Hourly division in which TX was measured
# T10N      : Minimum temperatuur op 10 cm hoogte (in 0.1 graden Celsius) / Minimum temperature at 10 cm above surface (in 0.1 degrees Celsius)
# T10NH     : 6-uurs tijdvak waarin T10N is gemeten / 6-hourly division in which T10N was measured; 6=0-6 UT; 12=6-12 UT; 18=12-18 UT; 24=18-24 UT
# SQ        : Zonneschijnduur (in 0.1 uur) berekend uit de globale straling (-1 voor <0.05 uur) / Sunshine duration (in 0.1 hour) calculated from global radiation (-1 for <0.05 hour)
# SP        : Percentage van de langst mogelijke zonneschijnduur / Percentage of maximum potential sunshine duration
# Q         : Globale straling (in J/cm2) / Global radiation (in J/cm2)
# DR        : Duur van de neerslag (in 0.1 uur) / Precipitation duration (in 0.1 hour)
# RH        : Etmaalsom van de neerslag (in 0.1 mm) (-1 voor <0.05 mm) / Daily precipitation amount (in 0.1 mm) (-1 for <0.05 mm)
# RHX       : Hoogste uursom van de neerslag (in 0.1 mm) (-1 voor <0.05 mm) / Maximum hourly precipitation amount (in 0.1 mm) (-1 for <0.05 mm)
# RHXH      : Uurvak waarin RHX is gemeten / Hourly division in which RHX was measured
# PG        : Etmaalgemiddelde luchtdruk herleid tot zeeniveau (in 0.1 hPa) berekend uit 24 uurwaarden / Daily mean sea level pressure (in 0.1 hPa) calculated from 24 hourly values
# PX        : Hoogste uurwaarde van de luchtdruk herleid tot zeeniveau (in 0.1 hPa) / Maximum hourly sea level pressure (in 0.1 hPa)
# PXH       : Uurvak waarin PX is gemeten / Hourly division in which PX was measured
# PN        : Laagste uurwaarde van de luchtdruk herleid tot zeeniveau (in 0.1 hPa) / Minimum hourly sea level pressure (in 0.1 hPa)
# PNH       : Uurvak waarin PN is gemeten / Hourly division in which PN was measured
# VVN       : Minimum opgetreden zicht / Minimum visibility; 0: <100 m; 1:100-200 m; 2:200-300 m;...; 49:4900-5000 m; 50:5-6 km; 56:6-7 km; 57:7-8 km;...; 79:29-30 km; 80:30-35 km; 81:35-40 km;...; 89: >70 km
# VVNH      : Uurvak waarin VVN is gemeten / Hourly division in which VVN was measured
# VVX       : Maximum opgetreden zicht / Maximum visibility; 0: <100 m; 1:100-200 m; 2:200-300 m;...; 49:4900-5000 m; 50:5-6 km; 56:6-7 km; 57:7-8 km;...; 79:29-30 km; 80:30-35 km; 81:35-40 km;...; 89: >70 km)
# VVXH      : Uurvak waarin VVX is gemeten / Hourly division in which VVX was measured
# NG        : Etmaalgemiddelde bewolking (bedekkingsgraad van de bovenlucht in achtsten; 9=bovenlucht onzichtbaar) / Mean daily cloud cover (in octants; 9=sky invisible)
# UG        : Etmaalgemiddelde relatieve vochtigheid (in procenten) / Daily mean relative atmospheric humidity (in percents)
# UX        : Maximale relatieve vochtigheid (in procenten) / Maximum relative atmospheric humidity (in percents)
# UXH       : Uurvak waarin UX is gemeten / Hourly division in which UX was measured
# UN        : Minimale relatieve vochtigheid (in procenten) / Minimum relative atmospheric humidity (in percents)
# UNH       : Uurvak waarin UN is gemeten / Hourly division in which UN was measured
# EV24      : Referentiegewasverdamping (Makkink) (in 0.1 mm) / Potential evapotranspiration (Makkink) (in 0.1 mm)
# STN,YYYYMMDD,DDVEC,FHVEC,   FG,  FHX, FHXH,  FHN, FHNH,  FXX, FXXH,   TG,   TN,  TNH,   TX,  TXH, T10N,T10NH,   SQ,   SP,    Q,   DR,   RH,  RHX, RHXH,   PG,   PX,  PXH,   PN,  PNH,  VVN, VVNH,  VVX, VVXH,   NG,   UG,   UX,  UXH,   UN,  UNH, EV24
  209,20210101,  289,   29,   35,   70,    8,   10,   13,   90,    8,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  215,20210101,  219,   18,   21,   30,   11,   10,    1,   70,   11,   22,  -33,    2,   61,   15,  -35,    6,    8,   10,  162,    3,    3,    3,   11,10084,10113,   24,10061,    1,    0,    1,   70,   10,    8,   95,   99,    4,   87,   11,    2
  225,20210101,  268,   30,   38,   50,    2,   10,   16,  100,   18,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  235,20210101,  252,   12,   17,   30,    3,   10,    6,   50,    4,   44,   16,   10,   71,   15,   -3,   12,   28,   37,  247,    0,   -1,   -1,    1,10075,10104,   24,10051,    1,   65,    6,   75,    1,    7,   88,   96,   24,   75,    1,    3
  240,20210101,  211,   20,   23,   30,    2,   10,    8,   50,   12,   21,  -22,    3,   64,   14,  -41,    6,   18,   23,  217,    7,    5,    5,   10,10080,10109,   24,10057,    1,    1,    3,   70,   12,    6,   94,   98,    1,   86,   12,    2
  242,20210101,  295,   34,   41,   70,    1,   10,   23,  100,    2,   60,   33,    8,   83,   13,   18,   12,     ,     ,     ,     ,     ,     ,     ,10073,10102,   24,10047,    1,   58,   22,   75,    1,    6,   83,   92,   23,   72,   13,     
  248,20210101,  236,   22,   23,   30,   16,   20,    1,   60,   22,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  249,20210101,  226,   18,   21,   30,    4,   10,    1,   50,    5,   32,  -10,    2,   67,   14,  -39,    6,   37,   48,  269,    9,    6,    3,    6,     ,     ,     ,     ,     ,   29,    3,   65,    6,     ,   95,   98,   17,   87,   12,    3
  251,20210101,  276,   25,   28,   40,    1,   20,    5,   80,    1,   42,    2,    6,   79,   12,  -16,   12,   23,   30,  218,   11,    9,    3,   15,10069,10097,   24,10041,    1,   64,    1,   70,   11,     ,   93,   97,    6,   81,   12,    3
  257,20210101,     ,     ,     ,     ,     ,     ,     ,     ,     ,   52,   -5,    1,   70,   15,  -19,    6,   29,   38,  231,   25,   18,    4,    7,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   86,   98,   17,   69,    4,    3
  258,20210101,  236,   41,   43,   50,    4,   30,   14,   80,    7,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  260,20210101,  225,   21,   21,   30,    6,   10,    1,   60,   15,   30,  -35,    3,   57,   14,  -30,    6,    9,   12,  194,    0,    0,    0,    1,10084,10113,   24,10059,    1,    0,    2,   70,   11,    7,   92,   98,    1,   85,   15,    2
  267,20210101,  238,   32,   33,   40,    3,   20,   16,   60,    5,   38,    5,    1,   57,   13,  -18,    6,   11,   14,  182,    1,    1,    1,   21,     ,     ,     ,     ,     ,   57,    2,   70,   13,    7,   93,   98,   16,   89,    3,    2
  269,20210101,  211,   21,   22,   40,   24,   10,   11,   50,   14,   19,  -19,    2,   57,   14,  -47,    6,   32,   41,  256,    5,    1,    1,    7,10080,10109,   24,10055,    1,    1,    1,   68,   14,    6,   95,   99,    1,   86,   13,    3
  270,20210101,  233,   25,   26,   30,    1,   20,    4,   50,   13,   24,  -12,    8,   62,   15,  -33,   12,   36,   47,  251,    2,    1,    1,   22,10072,10100,   24,10046,    1,   50,    3,   70,   12,    6,   95,   97,    5,   89,   14,    3
  273,20210101,  219,   20,   20,   30,    3,   10,   14,   50,   20,   24,    1,    2,   53,   14,  -16,    6,   12,   16,  197,    3,    1,    1,    8,     ,     ,     ,     ,     ,   21,    4,   70,   14,     ,   96,   98,    1,   90,   14,    2
  275,20210101,  204,   16,   18,   30,   14,    0,    1,   50,   23,   15,  -31,    6,   48,   14,  -40,    6,    9,   12,  184,    0,   -1,   -1,    1,10085,10115,   24,10059,    1,    0,    3,   59,   14,    8,   98,   99,    1,   95,   15,    2
  277,20210101,  232,   34,   35,   40,    1,   30,    2,   70,   11,   36,    9,    3,   69,   14,   -4,    6,   40,   53,  307,   12,    7,    4,   20,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   95,  100,    9,   85,   13,    4
  278,20210101,  218,   19,   19,   30,   24,   10,    1,   50,   19,   20,  -30,    5,   48,   14,  -58,    6,   14,   18,  190,    0,   -1,   -1,    1,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   95,   99,    2,   88,   14,    2
  279,20210101,  229,   25,   28,   40,   18,   20,    2,   50,   12,   22,  -16,    2,   51,   14,  -19,    6,   16,   21,  194,    6,    7,    6,    7,10076,10105,   24,10050,    1,    1,    2,   58,   13,    8,   96,   99,    2,   90,   14,    2
  280,20210101,  223,   26,   27,   40,   19,   20,    3,   50,   18,   19,  -23,    8,   57,   13,  -42,   12,   17,   22,  192,    0,    0,    0,    1,10071,10099,   24,10045,    1,   10,    8,   70,   13,    7,   96,   98,    1,   89,   13,    2
  283,20210101,  210,   16,   17,   20,    5,   10,    1,   50,   19,   18,  -19,    3,   44,   15,  -39,    6,    0,    0,  126,    4,    2,    2,   16,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   96,  100,    1,   92,   13,    1
  285,20210101,  243,   47,   51,   70,    1,   20,    4,   90,    1,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  286,20210101,  220,   33,   34,   50,   19,   20,    7,   70,   19,   29,   -2,    7,   49,   15,   -8,   12,   10,   13,  149,    9,    8,    8,   13,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   95,   98,    6,   93,    2,    2
  290,20210101,  201,   19,   20,   30,   19,   10,    1,   50,   22,   16,  -20,    4,   42,   15,  -41,    6,   12,   15,  169,    0,   -1,   -1,    1,10082,10112,   24,10055,    1,    0,    4,   57,   15,    8,   96,   99,    1,   91,   13,    2
  308,20210101,  264,   50,   58,   80,   15,   30,    5,  100,   17,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  310,20210101,  249,   50,   55,  100,   18,   20,    5,  120,   18,   45,   28,    2,   64,   12,   11,    6,   30,   38,  282,   13,   16,    9,    2,10093,10121,   24,10067,    1,   59,   22,   75,    8,    8,   84,   92,    5,   75,   12,    4
  312,20210101,  282,   57,   62,   80,    7,   20,    1,  100,   10,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  313,20210101,  278,   55,   64,   90,   16,   20,    3,  110,   16,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  315,20210101,  255,   52,   54,   70,   15,   20,    1,   90,   15,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  316,20210101,  275,   54,   58,   70,    7,   20,    2,  100,   17,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  319,20210101,  246,   29,   30,   40,   12,   10,    1,   70,   12,   32,   14,    3,   57,   12,    3,    6,   33,   42,  277,    0,   -1,   -1,    1,10097,10124,   24,10067,    1,   63,   24,   70,    4,     ,   88,   97,    7,   81,   12,    3
  323,20210101,  245,   37,   38,   60,   14,   20,    1,   80,   14,   34,    5,    2,   64,   12,   -8,    6,   22,   28,  272,   11,   13,    9,   19,10093,10120,   24,10065,    1,     ,     ,     ,     ,     ,   91,   97,    4,   81,   13,    3
  324,20210101,  246,   47,   49,   70,   17,   30,    1,   90,   17,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  330,20210101,  255,   43,   48,   70,    9,   20,    1,  100,    7,   48,    7,    1,   71,   12,  -21,    6,   24,   31,  215,   13,   11,    8,    8,10087,10115,   24,10064,    1,     ,     ,     ,     ,     ,   91,   97,    1,   85,   13,    3
  331,20210101,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  340,20210101,  238,   24,   25,   50,   16,   10,    1,   80,   16,   22,  -27,    6,   59,   14,  -54,    6,     ,     ,     ,   19,   12,    5,   18,10094,10123,   24,10064,    1,    0,    2,   70,   13,    7,   94,  100,    1,   84,   13,     
  343,20210101,  244,   35,   37,   60,   12,   20,    1,  100,   13,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,     
  344,20210101,  222,   23,   25,   40,   13,   10,    1,   70,   12,   30,  -33,    3,   69,   12,  -24,    6,   10,   13,  162,   18,   18,    7,   14,10086,10115,   24,10062,    1,    0,    1,   70,   12,    8,   94,   99,    1,   83,   12,    2
  348,20210101,  225,   30,   30,   40,   12,   20,    1,   60,   12,   25,  -34,    2,   54,   13,  -55,    6,   16,   20,  210,    4,    1,    1,   14,10085,10115,   24,10061,    1,    0,    1,   65,   11,     ,   96,   98,    1,   91,   11,    2
  350,20210101,  231,   23,   23,   30,   11,   10,    1,   60,   15,   29,    7,    4,   59,   15,    0,    6,   32,   40,  251,    9,    5,    4,   12,10091,10122,   24,10063,    1,    4,    2,   70,   15,    8,   93,   98,    1,   81,   15,    3
  356,20210101,  231,   29,   29,   40,   11,   10,    1,   70,   13,   25,  -16,    4,   54,   15,  -34,    6,   11,   14,  207,    5,    2,    1,   19,10087,10116,   24,10061,    1,     ,     ,     ,     ,     ,   95,  100,    4,   91,   13,    2
  370,20210101,  229,   25,   27,   40,   12,   10,    1,   60,   12,   25,    2,    5,   55,   12,   -5,    6,   23,   29,  267,    0,   -1,   -1,    1,10092,10124,   24,10062,    1,   11,    3,   70,   12,    8,   94,   98,    2,   85,   12,    3
  375,20210101,  231,   29,   30,   40,   13,   10,    1,   60,   14,   24,   -9,    8,   61,   13,  -20,   12,   21,   27,  275,    8,    4,    3,   20,10089,10121,   24,10061,    1,    5,    4,   70,   12,    8,   93,   98,    3,   82,   12,    3
  377,20210101,  222,   18,   19,   30,   18,   10,    1,   50,   13,   19,    1,   19,   35,   15,  -15,   24,    4,    5,  177,    7,    3,    2,   16,     ,     ,     ,     ,     ,   27,    4,   64,   14,    7,   96,   98,    2,   93,    1,    2
  380,20210101,  228,   21,   23,   30,   10,   10,    3,   50,   11,   20,    1,   22,   36,   13,   -6,   24,   11,   14,  238,    0,   -1,   -1,    1,10098,10133,   24,10061,    1,   22,    5,   62,   15,    8,   92,   96,    1,   86,   14,    3
  391,20210101,  220,   15,   16,   20,   10,   10,    1,   40,   11,   25,    4,    9,   54,   14,   -8,   12,   22,   28,  284,    0,    0,    0,    1,     ,     ,     ,     ,     ,     ,     ,     ,     ,     ,   95,   99,    1,   86,   13,    3
```

**Comment by ymampaey** [comment]
In the code below is a working python example, building on @jschuitemaker.
It builds the parameter string corresponding to the new KNMI api version (eg. start=20210101&end=20210101&stns=260).
Dropping the lines starting with # and converting to a DataFrame.
Inputs are specified in main().
Outputs:
```
df
   STN  YYYYMMDD   EV24     TG     TN     DR     RH
0  240  20210101      2     21    -22      7      5
1  240  20210102      3     26      2      6      8
2  240  20210103      2     37     28      0     -1
```
Code:
```
import requests
import pandas as pd
from io import StringIO


def main():
    startdate = '20210101'
    enddate = '20210103'
    stations = [240]
    variables = ['EV24', 'TG', 'TN', 'DR', 'RH']
    df = get_daily_data_df(startdate, enddate, stations, variables)
    print(df)


def get_daily_data_df(startdate, enddate, stations, variables):
    """Request and parse data from knmi api.

    Parameters
    ----------
    start : str
        Startdate in string format, eg '20210101'
    end : str
        Enddate in string format, eg '20210101'
    stations : [int], optional
        List of station numbers in int format, by default None
    variables : [str], optional
        List of variables in str format, if None is given, all are returned by the api

    Returns
    -------
    DataFrame
        Containing data returned by knmi api
    """
    r = get_daily_data_raw(startdate, enddate, stations, variables)
    df = parse_result_to_df(r)
    return df


def get_daily_data_raw(start, end, stations=None, variables=None):
    """Get raw data from knmi api.
    
    See: https://www.knmi.nl/kennis-en-datacentrum/achtergrond/data-ophalen-vanuit-een-script
    Parameters
    ----------
    start : str
        Startdate in string format, eg '20210101'
    end : str
        Enddate in string format, eg '20210101'
    stations : [int], optional
        List of station numbers in int format, by default None
    variables : [str], optional
        List of variables in str format, if None is given, all are returned by the api

    Returns
    -------
    str
        Containing data returned by knmi api
    """
    url = 'https://www.daggegevens.knmi.nl/klimatologie/daggegevens'
    params = 'start=' + start
    params = params + '&end=' + end
    params = add_list_items_to_params(params, 'stns', stations)
    params = add_list_items_to_params(params, 'vars', variables)
    r = requests.post(url=url, data=params)
    return r.text


def add_list_items_to_params(params, name, variables):
    """Add every variable in var_list to the parameter string.

    Parameters
    ----------
    params : str
        String containing the request parameters
    name : str
        Name of the variable, specified by knmi api
    variables : list
        Containing items to be added to params

    Returns
    -------
    str
        Appended string of request parameters
    """
    if variables is not None:
        vars_parsed = str(variables[0])
        if len(variables) != 1:
            for var in variables[1:]:
                vars_parsed = vars_parsed + ':' + str(var)
        params = params + '&' + name + '=' + vars_parsed
    return params


def parse_result_to_df(response_text):
    """Parse result of function get_daily_data_raw

    Parameters
    ----------
    response_text : str
        Containing data returned by knmi api

    Returns
    -------
    DataFrame
        Containing data returned by knmi api
    """
    # Count and drop the # lines, except last containing column names
    count = 0
    for i in range(0, len(response_text)):
        if (response_text[i] == '#'):
            count = count + 1
    r = response_text.split("\n", count-1)[count-1]
    # drop '# '
    r = r[2:]
    df = pd.read_csv(StringIO(r))
    return df


if __name__ == '__main__':
    main()
```

**Comment by teije01** [comment]
I spent some time today fixing the bugs that were introduced by a format change in the knmi api output :fire: :see_no_evil: 

Hope you agree with these changes.

One thing I noticed (and I did not change for backwards compatibility) is that you shift the hours from the knmi by 1 hour using the hourly dataframe retrieval. I only use the daily method, so it does not affect me, but it may lead to unexpected behavior on the user side
